name: Keep Supabase Alive (Test Version)

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 */5 * *'  # Every 5 days at midnight

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X POST 'https://jomzhsbkofcoocqhqsol.supabase.co/rest/v1/rpc/ping' \
               -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbXpoc2Jrb2Zjb29jcWhxc29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzU5MzYsImV4cCI6MjA2NjQxMTkzNn0.YhP1cyQXwEXxcLkz22eEc5olCoSIiYccLmqoCjS8Dog" \
               -H "Content-Type: application/json" \
               -H "Accept: application/json" \
               --data '{}'
